//! PLONK proving data types loaded from gnark's exported binary files.
//!
//! These types represent the proving key, constraint system selectors,
//! and permutation polynomials in GPU-friendly format.

use crate::{BN254Fr, BN254G1Affine};

/// PLONK proving data loaded from gnark's exported binary files.
/// Created by `ExportPlonkBn254Data` (Go side) and loaded by `PlonkProvingData::load`.
pub struct PlonkProvingData {
    /// Domain size N = 2^k (number of constraints rounded to power of 2)
    pub domain_size: usize,

    /// Log2 of domain size
    pub lg_domain_size: u32,

    /// Domain generator (omega) — the N-th root of unity in Fr
    pub omega: BN254Fr,

    /// Number of public variables (first NbPublic constraints are placeholders)
    pub nb_public_variables: usize,

    /// Coset shift k1 (FrMultiplicativeGen, = 5 for BN254)
    pub coset_shift: BN254Fr,

    /// KZG SRS in Lagrange basis (N affine G1 points, for polynomial commitments)
    pub srs_lagrange: Vec<BN254G1Affine>,

    /// KZG SRS in canonical/monomial basis (N+3 affine G1 points, for opening proofs)
    pub srs_canonical: Vec<BN254G1Affine>,

    /// Selector polynomials in Lagrange form (N Fr elements each)
    pub ql: Vec<BN254Fr>,
    pub qr: Vec<BN254Fr>,
    pub qm: Vec<BN254Fr>,
    pub qo: Vec<BN254Fr>,
    pub qk: Vec<BN254Fr>,

    /// BSB22 selector polynomials (Qcp, 1 for SP1's circuit).
    /// Qcp[i] is 1 at rows where committed wire values participate, 0 elsewhere.
    pub qcp: Vec<Vec<BN254Fr>>,

    /// BSB22 commitment constraint indexes.
    /// Each entry is the constraint row index where the BSB22 commitment value is injected.
    /// For SP1: exactly 1 entry (e.g., 25298720).
    pub commitment_constraint_indexes: Vec<usize>,

    /// Permutation polynomials in Lagrange form (N Fr elements each)
    pub s1: Vec<BN254Fr>,
    pub s2: Vec<BN254Fr>,
    pub s3: Vec<BN254Fr>,
}

impl PlonkProvingData {
    /// Load PLONK proving data from gnark's exported binary files.
    ///
    /// The files must have been generated by `ExportPlonkBn254Data` (Go side).
    /// Each file contains raw little-endian bytes (32 bytes per Fr, 64 bytes per G1 affine).
    pub fn load(dir: &str) -> anyhow::Result<Self> {
        use std::path::Path;

        let dir = Path::new(dir);

        // Load domain info (must be at least 88 bytes)
        let domain_info = std::fs::read(dir.join("plonk_domain_info.bin"))?;
        anyhow::ensure!(
            domain_info.len() >= 88,
            "plonk_domain_info.bin too short: {} bytes < 88",
            domain_info.len()
        );

        let domain_size = u64::from_le_bytes(domain_info[..8].try_into()?) as usize;
        anyhow::ensure!(
            domain_size.is_power_of_two() && domain_size >= 2,
            "domain_size {} is not a valid power of 2",
            domain_size
        );
        let lg_domain_size = domain_size.trailing_zeros();

        // Read domain generator (omega) — 32 bytes LE at offset 8
        let omega = BN254Fr::from_le_bytes(domain_info[8..40].try_into()?);

        // Read NbPublicVariables — uint64 LE at offset 40
        let nb_public_variables = u64::from_le_bytes(domain_info[40..48].try_into()?) as usize;

        // Read numCommitments at offset 48
        let num_commitments = u64::from_le_bytes(domain_info[48..56].try_into()?) as usize;

        // Read coset shift (FrMultiplicativeGen) — 32 bytes LE at offset 56
        let coset_shift = BN254Fr::from_le_bytes(domain_info[56..88].try_into()?);

        // Read commitment_constraint_indexes — numCommitments × uint64 LE at offset 88
        // (exported by Go after the coset shift; if not present, use empty vec)
        let mut commitment_constraint_indexes = Vec::with_capacity(num_commitments);
        let cci_start = 88;
        for i in 0..num_commitments {
            let offset = cci_start + i * 8;
            if offset + 8 <= domain_info.len() {
                let idx = u64::from_le_bytes(domain_info[offset..offset + 8].try_into()?) as usize;
                commitment_constraint_indexes.push(idx);
            }
        }

        // Load SRS points
        let srs_lagrange = load_g1_points(&dir.join("srs_g1_lagrange.bin"))?;
        let srs_canonical = load_g1_points(&dir.join("srs_g1_canonical.bin"))?;

        // Load selector polynomials
        let ql = load_fr_elements(&dir.join("trace_ql.bin"))?;
        let qr = load_fr_elements(&dir.join("trace_qr.bin"))?;
        let qm = load_fr_elements(&dir.join("trace_qm.bin"))?;
        let qo = load_fr_elements(&dir.join("trace_qo.bin"))?;
        let qk = load_fr_elements(&dir.join("trace_qk.bin"))?;

        // Load permutation polynomials
        let s1 = load_fr_elements(&dir.join("trace_s1.bin"))?;
        let s2 = load_fr_elements(&dir.join("trace_s2.bin"))?;
        let s3 = load_fr_elements(&dir.join("trace_s3.bin"))?;

        // Load BSB22 polynomials
        let mut qcp = Vec::new();
        let mut i = 0;
        loop {
            let path = dir.join(format!("trace_qcp_{}.bin", i));
            if path.exists() {
                qcp.push(load_fr_elements(&path)?);
                i += 1;
            } else {
                break;
            }
        }

        // Validate loaded vector sizes against domain_size
        anyhow::ensure!(
            srs_lagrange.len() >= domain_size,
            "SRS Lagrange has {} points, need {}",
            srs_lagrange.len(),
            domain_size
        );
        anyhow::ensure!(
            srs_canonical.len() >= domain_size + 3,
            "SRS canonical has {} points, need >= {} (domain_size + 3 for h-poly and linearization commits)",
            srs_canonical.len(),
            domain_size + 3
        );
        for (name, poly) in [
            ("ql", &ql),
            ("qr", &qr),
            ("qm", &qm),
            ("qo", &qo),
            ("qk", &qk),
            ("s1", &s1),
            ("s2", &s2),
            ("s3", &s3),
        ] {
            anyhow::ensure!(
                poly.len() == domain_size,
                "{name} length {} != domain_size {}",
                poly.len(),
                domain_size
            );
        }
        for (i, q) in qcp.iter().enumerate() {
            anyhow::ensure!(
                q.len() == domain_size,
                "qcp_{i} length {} != domain_size {}",
                q.len(),
                domain_size
            );
        }

        // Validate commitment_constraint_indexes matches qcp count
        if !commitment_constraint_indexes.is_empty() || !qcp.is_empty() {
            anyhow::ensure!(
                commitment_constraint_indexes.len() == qcp.len(),
                "commitment_constraint_indexes count ({}) != qcp count ({}). \
                 Ensure the Go exporter writes indexes at offset 88 of plonk_domain_info.bin.",
                commitment_constraint_indexes.len(),
                qcp.len()
            );
        }
        // Validate each index is within the domain
        for (i, &idx) in commitment_constraint_indexes.iter().enumerate() {
            anyhow::ensure!(
                nb_public_variables + idx < domain_size,
                "commitment_constraint_indexes[{i}] = {idx}: \
                 nb_public_variables ({nb_public_variables}) + index ({idx}) >= domain_size ({domain_size})"
            );
        }

        tracing::info!(
            domain_size,
            lg_domain_size,
            nb_public_variables,
            srs_lagrange_len = srs_lagrange.len(),
            srs_canonical_len = srs_canonical.len(),
            num_qcp = qcp.len(),
            num_cci = commitment_constraint_indexes.len(),
            "Loaded PLONK proving data"
        );

        Ok(Self {
            domain_size,
            lg_domain_size,
            omega,
            nb_public_variables,
            coset_shift,
            srs_lagrange,
            srs_canonical,
            ql,
            qr,
            qm,
            qo,
            qk,
            qcp,
            commitment_constraint_indexes,
            s1,
            s2,
            s3,
        })
    }
}

/// Per-proof witness data loaded from ExportSolvedWitness (Go side).
/// Contains wire assignments (L, R, O) and BSB22 committed polynomials + commitments.
pub struct PlonkWitnessData {
    /// Wire assignment L in Lagrange basis (N Fr elements, canonical LE)
    pub l: Vec<BN254Fr>,
    /// Wire assignment R
    pub r: Vec<BN254Fr>,
    /// Wire assignment O
    pub o: Vec<BN254Fr>,
    /// BSB22 committed polynomials in Lagrange basis (1 per commitment for SP1)
    pub bsb22_polys: Vec<Vec<BN254Fr>>,
    /// BSB22 KZG commitment points (1 per commitment for SP1)
    pub bsb22_commitments: Vec<BN254G1Affine>,
}

impl PlonkWitnessData {
    /// Load per-proof witness data from ExportSolvedWitness output files.
    pub fn load(dir: &str) -> anyhow::Result<Self> {
        use std::path::Path;
        let dir = Path::new(dir);

        // Load witness info metadata
        let info = std::fs::read(dir.join("witness_info.bin"))?;
        anyhow::ensure!(info.len() >= 24, "witness_info.bin too short: {} bytes < 24", info.len());

        let domain_size = u64::from_le_bytes(info[..8].try_into()?) as usize;
        let _nb_public = u64::from_le_bytes(info[8..16].try_into()?) as usize;
        let num_commitments = u64::from_le_bytes(info[16..24].try_into()?) as usize;

        // Load wire assignments
        let l = load_fr_elements(&dir.join("witness_l.bin"))?;
        let r = load_fr_elements(&dir.join("witness_r.bin"))?;
        let o = load_fr_elements(&dir.join("witness_o.bin"))?;

        anyhow::ensure!(
            l.len() == domain_size,
            "L length {} != domain_size {}",
            l.len(),
            domain_size
        );
        anyhow::ensure!(
            r.len() == domain_size,
            "R length {} != domain_size {}",
            r.len(),
            domain_size
        );
        anyhow::ensure!(
            o.len() == domain_size,
            "O length {} != domain_size {}",
            o.len(),
            domain_size
        );

        // Load BSB22 committed polynomials and commitment points
        let mut bsb22_polys = Vec::with_capacity(num_commitments);
        let mut bsb22_commitments = Vec::with_capacity(num_commitments);
        for i in 0..num_commitments {
            let poly = load_fr_elements(&dir.join(format!("bsb22_poly_{i}.bin")))?;
            anyhow::ensure!(
                poly.len() == domain_size,
                "bsb22_poly_{i} length {} != domain_size {}",
                poly.len(),
                domain_size
            );
            bsb22_polys.push(poly);

            let points = load_g1_points(&dir.join(format!("bsb22_commitment_{i}.bin")))?;
            anyhow::ensure!(
                points.len() == 1,
                "bsb22_commitment_{i} has {} points, expected 1",
                points.len()
            );
            bsb22_commitments.push(points[0]);
        }

        tracing::info!(domain_size, num_commitments, "Loaded PLONK witness data");

        Ok(Self { l, r, o, bsb22_polys, bsb22_commitments })
    }

    /// Extract public inputs from the L wire (first nb_public_variables values).
    pub fn public_inputs(&self, nb_public_variables: usize) -> Vec<BN254Fr> {
        self.l[..nb_public_variables.min(self.l.len())].to_vec()
    }
}

fn load_g1_points(path: &std::path::Path) -> anyhow::Result<Vec<BN254G1Affine>> {
    use crate::fields::Fq;

    let data = std::fs::read(path)?;
    anyhow::ensure!(
        data.len() % 64 == 0,
        "{}: file size {} not a multiple of 64",
        path.display(),
        data.len()
    );
    let n = data.len() / 64;
    let mut points = Vec::with_capacity(n);
    for i in 0..n {
        let offset = i * 64;
        // Load raw LE bytes into temporary Fq limb containers.
        // gnark exports G1 coordinates as CANONICAL (non-Montgomery) little-endian:
        //   RawBytes() calls BigEndian.PutElement() which calls fromMont(),
        //   then writeG1File() calls reverseBytes() to produce LE.
        // We must convert canonical → Montgomery so that BN254G1Affine always
        // holds Montgomery-form coordinates, matching what GPU MSM (sppark mont_t)
        // and CPU Fq arithmetic expect.
        let mut canonical_x = crate::BN254Fq { limbs: [0; 8] };
        let mut canonical_y = crate::BN254Fq { limbs: [0; 8] };
        unsafe {
            std::ptr::copy_nonoverlapping(
                data[offset..].as_ptr(),
                canonical_x.limbs.as_mut_ptr() as *mut u8,
                32,
            );
            std::ptr::copy_nonoverlapping(
                data[offset + 32..].as_ptr(),
                canonical_y.limbs.as_mut_ptr() as *mut u8,
                32,
            );
        }
        let mont_x = Fq::from_bn254fq_canonical(&canonical_x);
        let mont_y = Fq::from_bn254fq_canonical(&canonical_y);
        points.push(BN254G1Affine { x: mont_x.to_bn254fq_raw(), y: mont_y.to_bn254fq_raw() });
    }
    Ok(points)
}

fn load_fr_elements(path: &std::path::Path) -> anyhow::Result<Vec<BN254Fr>> {
    let data = std::fs::read(path)?;
    anyhow::ensure!(
        data.len() % 32 == 0,
        "{}: file size {} not a multiple of 32",
        path.display(),
        data.len()
    );
    let n = data.len() / 32;
    let mut elements = Vec::with_capacity(n);
    for i in 0..n {
        let offset = i * 32;
        let mut elem = BN254Fr { limbs: [0; 8] };
        unsafe {
            std::ptr::copy_nonoverlapping(
                data[offset..].as_ptr(),
                elem.limbs.as_mut_ptr() as *mut u8,
                32,
            );
        }
        elements.push(elem);
    }
    Ok(elements)
}
