[package]
name = "sp1-recursion-gnark-ffi"
description = "FFI bindings to Gnark for SP1"
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
rust-version = { workspace = true }

[dependencies]
slop-algebra = { workspace = true }
slop-symmetric = { workspace = true }
sp1-recursion-compiler = { workspace = true }
sp1-primitives = { workspace = true }
sp1-hypercube = { workspace = true }
sp1-verifier = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tempfile = { workspace = true }
num-bigint = { workspace = true }
cfg-if = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
sp1-gpu-groth16 = { path = "../../../sp1-gpu/crates/groth16" }

[build-dependencies]
bindgen = { workspace = true }
cfg-if = { workspace = true }

[dev-dependencies]
dirs = "5.0.1"
ark-bn254 = { version = "0.5", default-features = false, features = ["std", "curve"] }
ark-ec = { version = "0.5", default-features = false, features = ["parallel"] }
ark-ff = { version = "0.5", default-features = false, features = ["parallel"] }
ark-serialize = { version = "0.5", default-features = false }

[[example]]
name = "bench_groth16"
required-features = ["native"]

[features]
native = []
groth16-cuda = []
cuda = ["sp1-gpu-groth16/cuda"]

[lints]
workspace = true
