//! A benchmark program that exercises many RISC-V opcodes without using precompiles.
//! The `n` parameter controls the number of iterations (complexity).
//!
//! Opcodes exercised:
//!   ADD, SUB, MUL, DIV/REM, AND, OR, XOR, SLL, SRL, SRA, SLT, SLTU,
//!   LW, SW, LH, SH, LB, SB, BEQ, BNE, BLT, BGE, JAL, JALR, LUI, AUIPC
//!
//! No precompiles (SHA256, Keccak, EC, etc.) are used.

#![no_main]
sp1_zkvm::entrypoint!(main);

/// Simple PRNG (xorshift32) to generate varied inputs without external dependencies.
#[inline(always)]
fn xorshift32(state: &mut u32) -> u32 {
    let mut x = *state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    *state = x;
    x
}

pub fn main() {
    let n = sp1_zkvm::io::read::<u32>();
    sp1_zkvm::io::commit(&n);

    let mut rng_state: u32 = 0xDEADBEEF;
    let mut accum: u64 = 0;

    // Working arrays to exercise loads/stores at various widths
    let mut arr32: [u32; 256] = [0u32; 256];
    let mut arr16: [u16; 256] = [0u16; 256];
    let mut arr8: [u8; 256] = [0u8; 256];

    // Initialize arrays
    for i in 0..256 {
        arr32[i] = xorshift32(&mut rng_state);
        arr16[i] = (arr32[i] & 0xFFFF) as u16;
        arr8[i] = (arr32[i] & 0xFF) as u8;
    }

    for _iter in 0..n {
        let a = xorshift32(&mut rng_state);
        let b = xorshift32(&mut rng_state) | 1; // ensure non-zero for div
        let idx = (a as usize) & 0xFF;

        // === Arithmetic (ADD, SUB, MUL, DIV, REM) ===
        let sum = a.wrapping_add(b);
        let diff = a.wrapping_sub(b);
        let prod = a.wrapping_mul(b);
        let quot = a / b;
        let rem = a % b;

        // === Wide multiply (MULH, MULHU, MULHSU) ===
        let wide = (a as u64).wrapping_mul(b as u64);
        let hi = (wide >> 32) as u32;

        // === Bitwise (AND, OR, XOR) ===
        let and_val = a & b;
        let or_val = a | b;
        let xor_val = a ^ b;

        // === Shifts (SLL, SRL, SRA) ===
        let shift_amt = (b & 31) as u32;
        let sll = a << shift_amt;
        let srl = a >> shift_amt;
        let sra = ((a as i32) >> shift_amt) as u32;

        // === Comparisons (SLT, SLTU) ===
        let slt = if (a as i32) < (b as i32) { 1u32 } else { 0u32 };
        let sltu = if a < b { 1u32 } else { 0u32 };

        // === Word loads/stores (LW, SW) ===
        arr32[idx] = sum.wrapping_add(arr32[(idx + 1) & 0xFF]);
        let loaded32 = arr32[(idx + 2) & 0xFF];

        // === Half-word loads/stores (LH, SH) ===
        arr16[idx] = (diff & 0xFFFF) as u16;
        let loaded16 = arr16[(idx + 3) & 0xFF] as u32;

        // === Byte loads/stores (LB, SB) ===
        arr8[idx] = (prod & 0xFF) as u8;
        let loaded8 = arr8[(idx + 4) & 0xFF] as u32;

        // === Branches (BEQ, BNE, BLT, BGE, BLTU, BGEU) ===
        let branch_val = if sum == diff {
            xor_val  // BEQ taken
        } else if and_val != or_val {
            sll      // BNE taken
        } else if (srl as i32) < (sra as i32) {
            quot     // BLT taken
        } else if a >= b {
            rem      // BGE taken
        } else {
            hi       // fallthrough
        };

        // === LUI / AUIPC (generated by loading large immediates) ===
        let big_const: u32 = 0xABCDE000; // LUI for upper bits
        let combined = branch_val.wrapping_add(big_const);

        // Accumulate everything to prevent dead code elimination
        accum = accum.wrapping_add(
            (sum as u64)
                ^ (diff as u64)
                ^ (prod as u64)
                ^ (quot as u64)
                ^ (rem as u64)
                ^ (and_val as u64)
                ^ (or_val as u64)
                ^ (xor_val as u64)
                ^ (sll as u64)
                ^ (srl as u64)
                ^ (sra as u64)
                ^ (slt as u64)
                ^ (sltu as u64)
                ^ (loaded32 as u64)
                ^ (loaded16 as u64)
                ^ (loaded8 as u64)
                ^ (combined as u64)
                ^ (hi as u64),
        );
    }

    // Final reduction over arrays to ensure they aren't optimized away
    for i in 0..256 {
        accum = accum.wrapping_add(arr32[i] as u64);
        accum = accum.wrapping_add(arr16[i] as u64);
        accum = accum.wrapping_add(arr8[i] as u64);
    }

    let result_lo = accum as u32;
    let result_hi = (accum >> 32) as u32;
    sp1_zkvm::io::commit(&result_lo);
    sp1_zkvm::io::commit(&result_hi);
}
