[package]
name = "sp1-gpu-groth16"
description = "GPU-accelerated BN254 Groth16 prover for SP1"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
cuda = ["sp1-gpu-sys"]

[dependencies]
sha2 = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
rand = { workspace = true }
sp1-gpu-sys = { workspace = true, optional = true }
sp1-gpu-plonk = { path = "../plonk" }

[dev-dependencies]
num-bigint = { workspace = true }

[lints]
workspace = true
